django_example/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api', include('myapi.urls')),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('', views.index, name='index'),
    path('article/<int:article_id>', views.article, name='article'),
    path('article/<int:article_id>/post_comment', views.post_comment, name='post_comment'),
    path('article/create', views.article_create, name='article_create'),
    path('article/<int:article_id>/edit', views.article_edit, name='article_edit'),
    path('article/<int:article_id>/del', views.article_del, name='article_del'),
    # path('register', views.user_register, name='register'),
    # path('login', views.user_login, name='login'),
    path("profile", views.profile, name="profile"),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),

]

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime


class Profile(models.Model):
    user: User = models.OneToOneField(User, on_delete=models.CASCADE)
    user_img = models.CharField(max_length=200, blank=True)
    bio = models.TextField(max_length=500, blank=True)

    class Status(models.IntegerChoices):
        ADMIN = 1
        VISITOR = 10
        UNKNOWN = 20

    status = models.IntegerField(choices=Status.choices, default=Status.VISITOR)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"


class Article(models.Model):
    user: User = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    # article_author = models.CharField("Автор статьи", max_length=200, default="Admin")
    article_title = models.CharField("название статьи", max_length=200)
    article_text = models.TextField("текст статьи")
    article_introduction = models.TextField("Вступление статьи", default="...", max_length=500)
    introduction_img = models.CharField("картинка вступления", max_length=200, default="", blank=True)
    pub_date = models.DateTimeField("дата публикации")

    def username(self):
        return self.user.username if self.user else "NoName"

    def __str__(self):
        return self.article_title

    def was_publish_recently(self):
        return (timezone.now() - self.pub_date) <= datetime.timedelta(days=7)

    def get_introduction(self):
        return self.article_text[:150]

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField("имя автора", max_length=50)
    comment_text = models.CharField("текст коментария", max_length=200)
    pub_date = models.DateTimeField("дата публикации", default=datetime.datetime(2020, 2, 20), null=True)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

main/views.py
from django.http import HttpResponseRedirect, Http404, HttpRequest, HttpResponseForbidden
from django.urls import reverse
from django.utils import timezone
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages

from .forms import NewUserForm
from .models import Article


# Create your views here.

def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("main:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="main/register.html", context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("main:index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="main/login.html", context={"login_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("main:index")


def profile(request: HttpRequest):
    return render(request, 'main/profile.html')


def index(request: HttpRequest):
    last_articles = Article.objects.order_by('-pub_date')[:5]
    print(last_articles)
    return render(request, 'main/list.html', {"last_articles": last_articles})


def article(request: HttpRequest, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        raise Http404("Статья не найдена!")
    c = a.comment_set.order_by('-id')[:10]
    return render(request, 'main/article.html', {"article": a, "last_comments": c})


def article_create(request: HttpRequest):
    current_user = request.user
    if not request.user.is_authenticated:
        Http404("Пользователь не авторизован!")
    if request.method == "POST":
        a = Article(user=current_user,
                    article_title=request.POST['name'],
                    article_text=request.POST['text'].replace("<script", "<scripts"),
                    article_introduction=request.POST['intro'].replace("<script", "<scripts"),
                    pub_date=timezone.now(),
                    )
        a.save()
        return HttpResponseRedirect(reverse("main:index"))
    else:
        return render(request, 'main/article_edit.html', {"article": None})


def article_del(request: HttpRequest, article_id):
    if not request.user.is_authenticated:
        Http404("Пользователь не авторизован!")
    try:
        a: Article = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        raise Http404("Статья не найдена!")
    if not a.user or a.user.id != request.user.id:
        return HttpResponseForbidden("Ошибка доступа! " + str(a.user))
    a.delete()
    return HttpResponseRedirect(reverse("main:profile"))


def article_edit(request: HttpRequest, article_id):
    if not request.user.is_authenticated:
        Http404("Пользователь не авторизован!")
    try:
        a: Article = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        raise Http404("Статья не найдена!")
    if not a.user or a.user.id != request.user.id:
        return HttpResponseForbidden("Ошибка доступа! " + str(a.user))

    if request.method == "POST":
        a.article_title = request.POST['name']
        a.article_text = request.POST['text'].replace("<script", "<scripts")
        a.article_introduction = request.POST['intro'].replace("<script", "<scripts")
        a.pub_date = timezone.now()
        a.save()
        return HttpResponseRedirect(reverse("main:profile"))
    else:
        return render(request, 'main/article_edit.html', {"article": a})


def post_comment(request: HttpRequest, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        raise Http404("Статья не найдена!")

    a.comment_set.create(author_name=request.user.username, comment_text=request.POST['text'],
                         pub_date=timezone.now())
    return HttpResponseRedirect(reverse("main:article", args=(a.id,)) + "#comments")


def user_register(request: HttpRequest):
    if request.method == "POST":
        username, login, password = request.POST['username'], request.POST['login'], request.POST['password']
        return HttpResponseRedirect(reverse("main:login"))
    else:
        return render(request, 'main/user_register.html')


def user_login(request: HttpRequest):
    if request.method == "POST":
        login, password = request.POST['login'], request.POST['password']
        return HttpResponseRedirect(reverse("main:index"))
    else:
        return render(request, 'main/user_login.html')

main/templates/main/article.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}
    <div class="article-content container shadow-lg bg-white rounded p-4 mt-4">
        <div class="article-header mb-2">
            <div class="title">
                <h1>{{article.article_title}}</h1>
            </div>

            <div class="publish-meta text-secondary font-weight-bolder">
                <span class="article-author">
                    {% if article.user %}
                        {{article.user.username}}
                    {% else %}
                        Noname
                    {% endif %}
                </span>
                 ·
                <span class="article-date ">{{article.pub_date}}</span>
                {% if article.was_publish_recently %}
                     ·
                    <span class="article-new"> New </span>
                {% endif %}
            </div>


        </div>


        <div class="content">
            <p>{{article.article_text|safe}}</p>
        </div>







    </div>
    <div class="article-comments container shadow-lg bg-white rounded p-4 mt-4">
        <a name="comments"></a>
        <header class="comments-header">
            <h6>Последние комментарии:</h6>
        </header>

        <hr>
        {% if last_comments %}
<!--            <div class="cards">-->

            {% for c in last_comments %}
<!--                <div class="card mb-3">-->
<!--                    <div class="card-header bg-transparent border-primary">-->
<!--                    <div class="card-body border-primary border-dark">-->
                            <div class="article-comment">
                                <p class="article-comment-author"><strong class="text-right">{{c.author_name}}</strong>
                                    <span class="small">{{c.pub_date}}</span>   </p>
    <!--                        <hr>-->
                                <p class="article-comment-text card-text">{{c.comment_text}}</p>
                            </div>
<!--                    </div>-->
<!--                </div>-->
            {% endfor %}
<!--            </div>-->
        {% else %}
            Комментариев пока нет будьте первым =)
        {% endif %}

        <hr>

        <form action="{% url 'main:post_comment' article.id %}" method="post">
            {% csrf_token %}
            <textarea name="text" required placeholder="Текст комментария" cols="60" rows="6" class="form-control"></textarea><br>
            {% if user.is_authenticated %}
                <button type="submit" class="btn btn-success">Отправить комментарий</button>
            {% else %}
                <span class="warning">Чтобы писать комментарии надо <a href="{% url 'main:login' %}">авторизоваться</a></span>
            {% endif %}

        </form>
        <br>
    </div>
{% endblock %}

main/templates/main/article_edit.html
{% extends 'base.html' %}

{% block title %}Редактирвание статьи{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h4>Редактирвание статьи пользователя {{ user.username }}</h4>
        <form action="{% if article %} {% url 'main:article_edit' article.id %} {% else %} {% url 'main:article_create' %} {% endif %}" method="post">
            {% csrf_token %}
            <input value="{% if article %} {{ article.article_title}} {% endif %}" type="text"
                   required placeholder="Название статьи" name="name"
                   class="form-control col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3"><br>
            <textarea name="intro" required placeholder="Вступление статьи (html)" rows="8" class="form-control">{% if article %} {{ article.article_introduction}} {% endif %}</textarea><br>
            <textarea name="text" required placeholder="Текст статьи (html)" rows="16" class="form-control">{% if article %} {{ article.article_text}} {% endif %}</textarea><br>

            <button type="submit" class="btn btn-success">Сохранить</button>
        </form>
    {% else %}
        <p class="text-center">Вам необходимо <a href="{% url 'main:login' %}">войти</a> в систему</p>
    {% endif %}

{% endblock %}

main/templates/main/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Главная страница</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
</head>
<body>
    <h1>Главнейшая страница</h1>
    <img src="images/chrome-logo.png" alt="Imaaaaage" height="50px">
    <br>
    <p>Это - текст</p>

</body>
</html>

main/templates/main/list.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Последние статьи {% endblock %}

{% block content %}
    <script>


    </script>


    {% if last_articles %}
        <h2>Последние статьи:</h2>
        <br>
        <div class="list-articles cards" id="articles">
            {% for a in last_articles %}
                <script>
                    addArticleOfList(urlOfArticle({{a.id}}), `{{a.article_title}}`, `{{a.article_introduction|safe}}`,
                                     `{{a.introduction_img}}`, `{{a.pub_date|safe}}`, `{{a.user.username}}`)
                </script>
            {% endfor %}
        </div>
        <div class="center" id="end"></div>
        <script src="{% static 'main/js/articles.js' %}"></script>
    {% else %}
        Статей нет =(
    {% endif %}


{% endblock %}

main/templates/main/login.html
{% extends "base.html" %}

{% block title %} Вход {% endblock %}

{% block content %}      

{% load crispy_forms_tags %}

<!--Login--> 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>

{% endblock %}

main/templates/main/profile.html
{% extends 'base.html' %}

{% block title %} Профиль {% endblock %}

{% block content %}

<div class="container shadow-lg bg-white rounded">
    {% if user.is_authenticated %}
        <h4>Профиль</h4>
        <div class=" row align-items-end">
            <div class="col-2">
                {% if user.profile.user_img %}
                    <img src="{{user.profile.user_img}}" alt="mdo" width="128" height="128" class="rounded-sm">
                {% else %}
                    <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                      <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    </svg>
                {% endif %}
            </div>
            <div class="col-2">
                Пользователь <br>
                <span class="font-weight-bold" style="font-size: 20px">{{ user.username }}</span>
            </div>

        </div>
        <div>
            <h5>О себе:</h5>
            {% if user.profile.bio %}
                <p>{{ user.profile.bio }}</p>
            {% else %}
                <p>Нету</p>
            {% endif %}
        </div>

        <hr>

        <div>
            <h5>Публикации <a class="bt" href="{% url 'main:article_create' %}">Добавить</a></h5>
            {% if user.article_set %}
                {% for a in user.article_set.all %}
                    <p>
                        <h5><a href="{% url 'main:article' a.id %}">{{a.article_title}}</a></h5>
                        <a class="bt" href="{% url 'main:article_edit' a.id %}">Редактировать</a>
                        <a class="bt" href="{% url 'main:article_del' a.id %}" onclick="return confirm('Удалить статью?')">Удалить</a>
                    </p>
                {% endfor %}
            {% else %}
                <p>Нету</p>
            {% endif %}

        </div>
        <br>


    {% else %}
        <p class="text-center">Вам необходимо <a href="{% url 'main:login' %}">войти</a> в систему</p>
    {% endif %}
</div>

{% endblock %}

main/templates/main/register.html
{% extends "base.html" %}

{% block title %} Регистрация {% endblock %}

{% block content %} 

{% load crispy_forms_tags %}

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}

main/templates/main/user_login.html
{% extends 'base.html' %}

{% block title %} Регистрация {% endblock %}

{% block content %}

<div class="container col-5">
    <form class="px-4 py-3">
        <div class="form-group">
            <label for="FormEmail">Адрес электронной почты</label>
            <input type="email" class="form-control" id="FormEmail" placeholder="email@example.com">
        </div>
        <div class="form-group">
            <label for="password">Пароль</label>
            <input type="password" class="form-control" id="password" placeholder="Пароль">
        </div>


        <button type="submit" class="btn btn-primary" value="registration">Войти в систему</button>
    </form>
</div>

{% endblock %}

main/templates/main/user_register.html
{% extends 'base.html' %}

{% block title %} Регистрация {% endblock %}

{% block content %}
<div class="container col-5">
    <form class="px-4 py-3 shadow-lg bg-white rounded">
        <div class="form-group">
            <label for="FormEmail">Адрес электронной почты</label>
            <input type="email" class="form-control" id="FormEmail" placeholder="email@example.com">
        </div>
        <div class="form-group">
            <label for="FormUsername">Никнейм</label>
            <input type="username" class="form-control" id="FormUsername" placeholder="Никнейм">
        </div>
        <div class="form-group">
            <label for="password">Пароль</label>
            <input type="password" class="form-control" id="password" placeholder="Пароль">
        </div>
        <div class="form-group">
            <label for="confirm_password">Подтвердите пароль</label>
            <input type="password" class="form-control" id="confirm_password" placeholder="Подтвердите пароль"> <br>
        </div>

        <button type="submit" class="btn btn-primary" value="registration">Войти в систему</button>
        <br>
        <span>Уже зарегистрированы? Войдите</span>
    </form>
</div>

{% endblock %}