django_example/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api', include('myapi.urls')),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('', views.index, name='index'),
    path('article/<int:article_id>', views.article, name='article'),
    path('article/<int:article_id>/post_comment', views.post_comment, name='post_comment'),
    path('article/create', views.article_create, name='article_create'),
    path('article/<int:article_id>/edit', views.article_edit, name='article_edit'),
    path('article/<int:article_id>/del', views.article_del, name='article_del'),
    # path('register', views.user_register, name='register'),
    # path('login', views.user_login, name='login'),
    path("profile", views.profile, name="profile"),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),

]

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime


class Profile(models.Model):
    user: User = models.OneToOneField(User, on_delete=models.CASCADE)
    user_img = models.CharField(max_length=200, blank=True)
    bio = models.TextField(max_length=500, blank=True)

    class Status(models.IntegerChoices):
        ADMIN = 1
        VISITOR = 10
        UNKNOWN = 20

    status = models.IntegerField(choices=Status.choices, default=Status.VISITOR)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"


class Article(models.Model):
    user: User = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    # article_author = models.CharField("Автор статьи", max_length=200, default="Admin")
    article_title = models.CharField("название статьи", max_length=200)
    article_text = models.TextField("текст статьи")
    article_introduction = models.TextField("Вступление статьи", default="...", max_length=500)
    introduction_img = models.CharField("картинка вступления", max_length=200, default="", blank=True)
    pub_date = models.DateTimeField("дата публикации")

    def username(self):
        return self.user.username if self.user else "NoName"

    def __str__(self):
        return self.article_title

    def was_publish_recently(self):
        return (timezone.now() - self.pub_date) <= datetime.timedelta(days=7)

    def get_introduction(self):
        return self.article_text[:150]

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField("имя автора", max_length=50)
    comment_text = models.CharField("текст коментария", max_length=200)
    pub_date = models.DateTimeField("дата публикации", default=datetime.datetime(2020, 2, 20), null=True)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

main/views.py
from django.http import HttpResponseRedirect, Http404, HttpRequest, HttpResponseForbidden
from django.urls import reverse
from django.utils import timezone
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages

from .forms import NewUserForm
from .models import Article


# Create your views here.

def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("main:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="main/register.html", context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("main:index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="main/login.html", context={"login_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("main:index")


def profile(request: HttpRequest):
    return render(request, 'main/profile.html')


def index(request: HttpRequest):
    last_articles = Article.objects.order_by('-pub_date')[:5]
    print(last_articles)
    return render(request, 'main/list.html', {"last_articles": last_articles})


def article(request: HttpRequest, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        raise Http404("Статья не найдена!")
    c = a.comment_set.order_by('-id')[:10]
    return render(request, 'main/article.html', {"article": a, "last_comments": c})


def article_create(request: HttpRequest):
    current_user = request.user
    if not request.user.is_authenticated:
        Http404("Пользователь не авторизован!")
    if request.method == "POST":
        a = Article(user=current_user,
                    article_title=request.POST['name'],
                    article_text=request.POST['text'].replace("<script", "<scripts"),
                    article_introduction=request.POST['intro'].replace("<script", "<scripts"),
                    pub_date=timezone.now(),
                    )
        a.save()
        return HttpResponseRedirect(reverse("main:index"))
    else:
        return render(request, 'main/article_edit.html', {"article": None})


def article_del(request: HttpRequest, article_id):
    if not request.user.is_authenticated:
        Http404("Пользователь не авторизован!")
    try:
        a: Article = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        raise Http404("Статья не найдена!")
    if not a.user or a.user.id != request.user.id:
        return HttpResponseForbidden("Ошибка доступа! " + str(a.user))
    a.delete()
    return HttpResponseRedirect(reverse("main:profile"))


def article_edit(request: HttpRequest, article_id):
    if not request.user.is_authenticated:
        Http404("Пользователь не авторизован!")
    try:
        a: Article = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        raise Http404("Статья не найдена!")
    if not a.user or a.user.id != request.user.id:
        return HttpResponseForbidden("Ошибка доступа! " + str(a.user))

    if request.method == "POST":
        a.article_title = request.POST['name']
        a.article_text = request.POST['text'].replace("<script", "<scripts")
        a.article_introduction = request.POST['intro'].replace("<script", "<scripts")
        a.pub_date = timezone.now()
        a.save()
        return HttpResponseRedirect(reverse("main:profile"))
    else:
        return render(request, 'main/article_edit.html', {"article": a})


def post_comment(request: HttpRequest, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        raise Http404("Статья не найдена!")

    a.comment_set.create(author_name=request.user.username, comment_text=request.POST['text'],
                         pub_date=timezone.now())
    return HttpResponseRedirect(reverse("main:article", args=(a.id,)) + "#comments")


def user_register(request: HttpRequest):
    if request.method == "POST":
        username, login, password = request.POST['username'], request.POST['login'], request.POST['password']
        return HttpResponseRedirect(reverse("main:login"))
    else:
        return render(request, 'main/user_register.html')


def user_login(request: HttpRequest):
    if request.method == "POST":
        login, password = request.POST['login'], request.POST['password']
        return HttpResponseRedirect(reverse("main:index"))
    else:
        return render(request, 'main/user_login.html')

main/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}MySite{% endblock %}</title>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">


    <script src="{% static 'main/js/script.js' %}"></script>
</head>

<body style="background-color: rgb(238, 240, 242)">
<header class="p-3 mb-3 fixed-top sticky-top p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <div class="container d-flex flex-column flex-md-row align-items-center ">

        <h3 class="my-0 mr-md-auto font-weight-large "><a href="/" class="badge badge-dark" style="box-shadow: none;">Bimp</a></h3>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="/">Главная</a>
            <a class="p-2 text-dark" href="{% url 'main:article_create' %}">Добавить</a>
            <a class="p-2 text-dark" href="#">О проекте</a>
        </nav>
        <form class="col-12 col-lg-auto ">
            <input type="search" class="form-control" placeholder="Поиск..." aria-label="Search">
        </form>
        <div class="dropdown text-end">
            <a href="#" class="d-block  text-dark text-decoration-none" id="dropdownUser1" data-offset="0,10"
               data-toggle="dropdown" aria-expanded="false">

                {% if user.is_authenticated %}
                    {% if user.profile.user_img %}
                        <img src="{{user.profile.user_img}}" alt="mdo" width="32" height="32" class="rounded-circle">
                    {% else %}
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                          <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                        </svg>
                    {% endif %}
                {% else %}
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-person-x-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6.146-2.854a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708z"/>
                    </svg>
                {% endif %}
            </a>
            <ul class="dropdown-menu text-small dropdown-menu-right" aria-labelledby="dropdownMenuOffset">
                {% if user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'main:profile' %}">{{ user.username }}</a></li>
                    <li><a class="dropdown-item" href="{% url 'main:article_create' %}">Добавить</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'main:logout' %}">Выход</a></li>
                {% else %}
                    <li><a class="dropdown-item" href="{% url 'main:login' %}">Вход</a></li>
                    <li><a class="dropdown-item" href="{% url 'main:register' %}">Регистрация</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</header>

<div class="container">

    {% block content %} {% endblock %}
</div>

<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script> -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
</body>
</html>